skills = [
    "python",
    "java",
    "c",
    "c++",
    "sql",
    "html",
    "css",
    "javascript",
    "react",
    "node.js",
    "flask",
    "django",
    "streamlit",
    "git",
    "github",
    "machine learning",
    "deep learning",
    "artificial intelligence",
    "data science",
    "pandas",
    "numpy",
    "matplotlib",
    "tensorflow",
    "pytorch",
    "excel",
    "power bi",
    "tableau",
    "communication",
    "leadership",
    "teamwork",
    "problem solving"
]